version: "3.9"

services:
# front

# backend
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8080:8080"
    # dbに依存しているため記述
    depends_on: 
      - db

  db:
    image: postgres:16
    container_name: db
    ports:
      - 5432:5432
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testdb
    volumes:
      - ./database/init:/docker-entrypoint-initdb.d  # 初期データ
      - ./database/data:/var/lib/postgresql/data     # 永続化

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger-ui
    ports:
      - "8081:8080"
    volumes:
      - ./openapi.yml:/data/openapi.yml
    environment:
      SWAGGER_JSON: /data/openapi.yml